#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os
import imp

import django
from django.conf import settings


if __name__ == '__main__':
    args = sys.argv[1:]

    paths = [n for n in args if os.path.isfile(n)]

    print('alogator check%s: %s' % ('s' if len(paths) > 1 else '', ', '.join(paths)))

    for path in paths:
        if not settings.configured:
            settings_modul = imp.load_source('settings', path)
            settings.configure(**settings_modul.__dict__)

        if django.VERSION >= (1, 7):
            django.setup()

        from alogator.logwatch import logWatcher
        logWatcher()

    print('alogator done!')
